application: twitter-winner
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: ssl
  version: latest
- name: webapp2
  version: latest
- name: markupsafe
  version: latest
- name: setuptools
  version: latest
- name: jinja2
  version: latest
- name: lxml
  version: latest

handlers:
- url: /(favicon\.ico)
  mime_type: image/png
  static_files: static/\1
  upload: static/favicon\.ico
- url: /(robots\.txt)
  static_files: static/\1
  upload: static/robots\.txt
- url: /(img|css)/(.*)
  static_files: static/\1/\2
  upload: static/(img|css)/(.*)
- url: /.*
  script: main.application
  secure: always
